spring:
  application:
    name: cavavin
  #Data Source
  data:
    mongodb:
      #username: sa
      #password: Passw0rd
      host: localhost
      port: 27017
      database: cavavin
      #authentication-database: admin
      auto-index-creation: true

#Log
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG